name: Docker + Terraform CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
      working-directory: ./terraform

    - name: Get ECR Repo URL from Terraform Output
      id: ecr
      run: |
        echo "ECR_URL=$(terraform -chdir=./terraform output -raw ecr_repo_url)" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $ECR_URL

    - name: Build and Push Docker Image
      run: |
        docker build -t $ECR_URL:$IMAGE_TAG ./web-app
        docker push $ECR_URL:$IMAGE_TAG

    - name: Get ECS Task Public IP
      id: get-public-ip
      run: |
        CLUSTER_NAME=python-app-cluster
        SERVICE_NAME=python-app-service

        TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
        ENI_ID=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' --output text)
        PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query 'NetworkInterfaces[0].Association.PublicIp' --output text)

        echo "APP_URL=http://$PUBLIC_IP:5000" >> $GITHUB_ENV
        echo "Deployed App is accessible at: http://$PUBLIC_IP:5000"

    - name: Output App URL
      run: echo "✅ Open your deployed app at: $APP_URL"
 
